# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 884)
        MainWindow.setStyleSheet("/* 全局背景与文字颜色 */\n"
"QMainWindow {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* 侧边栏样式：深灰色背景，右侧带一条细边框 */\n"
"QFrame#side_bar {\n"
"    background-color: #2b2b2b;\n"
"    border-right: 1px solid #3d3d3d;\n"
"}\n"
"\n"
"/* 按钮样式：扁平化、圆角、青蓝色文字 */\n"
"QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    color: #00d4ff;\n"
"    font-family: \"Segoe UI\", \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #00d4ff;\n"
"}\n"
"\n"
"/* 滑动条样式微调 */\n"
"QSlider::handle:horizontal {\n"
"    background: #00d4ff;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 501))
        self.label.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 159, 34))
        self.pushButton.setStyleSheet("background-color: rgb(187, 212, 239);\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 520, 1071, 31))
        self.label_2.setStyleSheet("background-color: #d8e7f0;\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 120, 159, 34))
        self.pushButton_5.setStyleSheet("background-color: rgb(187, 212, 239);\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 360, 159, 34))
        self.pushButton_6.setStyleSheet("background-color: rgb(187, 212, 239);\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 450, 159, 34))
        self.pushButton_7.setStyleSheet("background-color: rgb(187, 212, 239);\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 10, 881, 501))
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("background-color: rgb(216, 231, 240);\n"
"font: 25pt \"Times New Roman\";\n"
"font: 25pt \"宋体\";\n"
"color:rgb(0,0,0);\n"
"font-weight: bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 551, 1071, 131))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setStyleSheet("/* 美化表头：实现加粗及中英文字体兼容 */\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0;\n"
"    padding: 2px;\n"
"    border: 1px solid #dcdcdc;\n"
"    /* 使用复合简写属性：粗细 字符大小 字体家族 */\n"
"    font: bold 12pt \"Times New Roman\", \"宋体\";\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* 统一表格内容风格 */\n"
"QTableWidget {\n"
"    background-color: #ffffff;\n"
"    gridline-color: #dcdcdc;\n"
"    border: 1px solid #bcbcbc;\n"
"    selection-background-color: #0078d7;\n"
"    /* 内容部分建议不加粗，以区分表头 */\n"
"    font: 12pt \"Times New Roman\", \"宋体\";\n"
"}")
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 200, 141, 21))
        self.horizontalSlider.setStyleSheet("/* 设置滑动条的凹槽（背景长条） */\n"
"QSlider::groove:horizontal {\n"
"    height: 8px; /* 凹槽的高度 */\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* 设置滑钮（中间那个圆块）的大小 */\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(187, 212, 239); /* 滑钮颜色 */\n"
"    width: 20px;         /* 关键属性：调节宽度 */\n"
"    height: 20px;        /* 关键属性：调节高度 */\n"
"    margin: -7px 0;      /* 关键技巧：负边距让滑钮垂直居中并突出凹槽 */\n"
"    border-radius: 10px; /* 圆角：设为宽高的一半即为圆形 */\n"
"    border: 1px solid rgb(187, 212, 239);\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 181, 31))
        self.label_4.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 181, 31))
        self.label_5.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 12pt \"Times New Roman\";\n"
"font: 12pt \"宋体\";\n"
"color:rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 280, 141, 21))
        self.horizontalSlider_2.setStyleSheet("/* 设置滑动条的凹槽（背景长条） */\n"
"QSlider::groove:horizontal {\n"
"    height: 8px; /* 凹槽的高度 */\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* 设置滑钮（中间那个圆块）的大小 */\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(187, 212, 239); /* 滑钮颜色 */\n"
"    width: 20px;         /* 关键属性：调节宽度 */\n"
"    height: 20px;        /* 关键属性：调节高度 */\n"
"    margin: -7px 0;      /* 关键技巧：负边距让滑钮垂直居中并突出凹槽 */\n"
"    border-radius: 10px; /* 圆角：设为宽高的一半即为圆形 */\n"
"    border: 1px solid rgb(187, 212, 239);\n"
"}")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1091, 691))
        self.widget.setStyleSheet("background-color: #ffffff")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.tableWidget.raise_()
        self.horizontalSlider.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.horizontalSlider_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWindowFilePath(_translate("MainWindow", "QMainWindow { background-color: #2b2b2b; color: white; }\\nQGroupBox { border: 1px solid #5e5e5e; margin-top: 10px; color: #00d4ff; }\\nQPushButton { background-color: #3d3d3d; border-radius: 5px; padding: 5px; color: white; }\\nQPushButton:hover { background-color: #007acc; }"))
        self.pushButton.setText(_translate("MainWindow", "加载图像"))
        self.label_2.setText(_translate("MainWindow", " 检测结果：共检测到  个类别，  个目标"))
        self.pushButton_5.setText(_translate("MainWindow", "加载模型"))
        self.pushButton_6.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_7.setText(_translate("MainWindow", "结果导出"))
        self.label_3.setText(_translate("MainWindow", "图像显示"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "中心点X坐标"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "中心点Y坐标"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "宽度"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "高度"))
        self.label_4.setText(_translate("MainWindow", "置信度阈值：0"))
        self.label_5.setText(_translate("MainWindow", "NMS阈值：0"))
